### ISSUE TITLE
simditor更新到2.3后报错

### ISSUE THREAD

**Issue by InfinityBlue** [mycolorway/simditor-checklist#3]
@editor.inputManager.addKeystrokeHandler '13', 'li', (e, $node) =>
报inputManager没有addKeystrokeHandler的方法

看了下simditor的源码改成@editor.keystroke.add后可以使用，不知道是不是正确的修复方法

**Comment by RuochenLyu** [comment]
感谢，刚发了个新版本。
https://github.com/mycolorway/simditor-checklist/releases/tag/v1.2.0
